name: Flutter CI

# This workflow is triggered on pushes to the main repository.

on: push

jobs:
    build:
        # This job will run on ubuntu virtual machine
      runs-on: ubuntu-latest

      # Within steps define actions we either explicitly write as flutter commands, or ones we get from the marketplace
      steps:

        # Setup Java environment in order to build the Android app.
        - uses: actions/checkout@v1
        - uses: actions/setup-java@v1
          with:
            java-version: '12.x'

        # Setup the flutter environment.
        - uses: subosito/flutter-action@v1
          with:
            channel: 'beta' # 'dev', 'alpha', default to: 'stable'
            flutter-version: '3.7.7' # you can also specify exact version of flutter
        # Get flutter dependencies.
        - run: flutter pub get

        # Check for any formatting issues in the code.
        - run: flutter format --set-exit-if-changed .

        # Statically analyze the Dart code for any errors.
        - run: flutter analyze .

        # Run widget tests for our flutter project.
        - run: flutter test

        # Build apk
        - run: flutter build apk
        - uses: actions/upload-artifact@v1
          with:
            # Name of the command/step.
            name: release-apk
            # Path to the release apk.
            path: build/app/outputs/apk/release/app-release.apk
